### ISSUE TITLE
Source of truth

### ISSUE THREAD

**Issue by arulagrawal** [Sighery/terraform-provider-njalla#66]
I've noticed that this provider does not act as a source of truth. I think if the aim is to manage dns through terraform, it probably should.

Example:
Create some records via terraform and some manually via the njalla website. Run terraform again, the manually created dns records are not removed.

Thanks again for this project, makes using njalla bearable.

**Comment by Sighery** [comment]
Hey @arulagrawal, thanks for using the provider and the feedback.

In this case, I wouldn't consider this a limitation of the provider, but rather a design choice of Terraform. Terraform can be the source of truth but at the end of the day it's just another way to interface with the provider.

I admit I'm mostly knowledgeable on the AWS provider, so other providers might work differently, but when using AWS and Terraform, nothing prevents you from going to the AWS console and creating resources manually there. Terraform won't know about them, and won't try to manage them.

So I wouldn't enforce on the provider code this constraint that everything has to go through Terraform or else it gets deleted. This constraint would probably better suited for the organisation/team workflow if you're using it within a company/team, or for yourself if you're using it on some personal project.

That being said, there's some things you can potentially do if you want to manage everything from your Terraform infra, although they don't fully solve your usecase:

### Import any resources you create manually

Terraform offers an `import` command you can use to read the remote resource data, and import it into a local resource so you can start managing it from within Terraform. There's more [documentation here](https://developer.hashicorp.com/terraform/cli/import), although for now this just affects the State file, and doesn't yet change the configuration files (so after you import it you need to manually fill in the resource data in your configuration files). [Here](https://registry.terraform.io/providers/Sighery/njalla/latest/docs/guides/importing-record-resources) more info on the syntax to import Njalla resources with this provider.

### Write some enforcer tool with the underlying library

This provider uses the underlying [gonjalla unofficial library](https://github.com/Sighery/gonjalla) to interface with the Njalla API. You could write some code that checks the Terraform state (perhaps you could re-use the [`terraform/states` Go library](https://pkg.go.dev/github.com/hashicorp/terraform@v0.15.3/states)?) and compares against the latest Njalla API, removing whatever is not in the Terraform state. Parsing the state file manually should also be an option as it's a JSON file. Another option would be to use a HCL parser to read the configuration files and get the resource names/data from there as well.

**Comment by arulagrawal** [comment]
I'm not too familiar with go + terraform myself, but I wonder if I could (eventually) modify this provider to allow for a flag (like source_of_truth = true) where this functionality would be implemented?

**Comment by Sighery** [comment]
You can try, but I'm not aware of any hooks system within the Terraform SDK. Closest I can think of is `ConfigureContextFunc` which you declare at the provider level to initialize the provider client with any necessary credentials, and then is passed over to the individual resources code: https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema#Provider

That being said, even if you could hack something like that together, I'd most likely not accept it into the provider code, as that's just not intended Terraform behaviour. If you want to really only manage infra from Terraform, you'd still need some tool running constantly and polling for changes, as otherwise if you don't run `terraform plan`/`terraform apply`, new resources created outside Terraform wouldn't be deleted.

**Comment by arulagrawal** [comment]
Thanks for the info, perhaps I should look at something more suited for my use case.

**Comment by Sighery** [comment]
Yeah, not sure Terraform would fit your usecase here. If you want to stick to a infrastructure-as-code tool, I'd point you to either [Terraform CDK](https://github.com/hashicorp/terraform-cdk) or [Pulumi](https://www.pulumi.com/). The point of these options is to enable you to write your infrastructure code within a familiar programming language, potentially allowing you to write more custom workflows than the basic create/update/delete/import available with Terraform HCL.

With CDK you might be able to write some code to plan/apply your infra + delete any infra created outside of the Terraform defined stuff. Similar thinking with Pulumi, but you'd need to check the provider configuration there. I know Pulumi can use Terraform providers, but I'm not sure what work is required for that, if it's a simple plug-and-play where you download the Terraform provider and use it within Pulumi, or if it requires custom development from either the provider dev, or Pulumi devs (or both).

If Pulumi fits your needs and it just requires some basic porting work, I'd be up for reviewing a PR, or potentially doing the job myself as I wanted to try out Pulumi and this would be a nice excuse (but can't guarantee any timeline if I were to do it myself).
