### ISSUE TITLE
You can not have both CNAME and TXT records

### ISSUE THREAD

**Issue by varac** [Sighery/terraform-provider-njalla#68]
I stumpled across this without changing any code.
After using this provider successfully for a while, I recently removed the TXT record and re-added it with excatly the same code, but 
trying to apply it now leads to a `You can not have both CNAME and TXT records` failure:

```
❯ tf apply  
...
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # njalla_record_txt.google-site-verification2 will be created
  + resource "njalla_record_txt" "google-site-verification2" {
      + content = "google-site-verification=..."
      + domain  = "....net"
      + id      = (known after apply)
      + name    = "@"
      + ttl     = 10800
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

njalla_record_txt.google-site-verification2: Creating...
╷
│ Error: Missing result map[error:map[code:%!s(float64=-32600) message:You can not have both CNAME and TXT records.] jsonrpc:2.0]
│ 
│   with njalla_record_txt.google-site-verification2,
│   on main.tf line 196, in resource "njalla_record_txt" "google-site-verification2":
│  196: resource "njalla_record_txt" "google-site-verification2" {
│ 
╵

❯ cat main.tf
terraform {
  required_providers {
    njalla = {
      source  = "Sighery/njalla"
      version = "0.10.0"
    }
  }
}
provider njalla {}

...

resource "njalla_record_txt" "google-site-verification2" {
  domain   = "....net"
  content  = "google-site-verification=..."
  ttl      = 10800
}
```

I'm pretty sure I was using the same Terraform version before and after (`1.1.9`), and also unsuccessfully tried upgrading to tf `1.3.4`.
So any help is appreciated.

**Comment by varac** [comment]
Hugh, I'm getting the same error in the njal.la UI, so it's definitvely an issue there, or it's layer 8 :)

**Comment by Sighery** [comment]
I admit I never use `CNAME` records, but yeah, I was going to say that sounds like a Njalla limitation. Either you have a CNAME record, or it thinks you do. You should be able to run the `list-records` API call with `curl` or some other utility (Postman) from your computer to know what the API output is, that should give you more info on what Njalla thinks you have. If you still can't see a `CNAME` record in there, you might need to contact their support for them to figure out what's wrong with your records.

**Comment by varac** [comment]
Turns out it's even a limitation by [RFC1034](https://www.rfc-editor.org/rfc/rfc1034), see also https://serverfault.com/questions/834320/adding-both-cname-and-txt-dns-records-for-one-subdomain
