### ISSUE TITLE
invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by cozybear-dev** [Sighery/terraform-provider-njalla#75]
Hi,

I've been using your provider for a while now, for which - thanks! Today I wanted to change some records, and I'm encountering an error I have not seen before. Trace logging in Terraform does not currently show the webrequest it's doing - it has been of little help thus far.

The error (running Terraform v1.8.3);

invalid character '<' looking for beginning of value

The code I'm running is in sync at; https://github.com/cozybear-dev/njalla-management/blob/main/main.tf

It affects both TXT, A and AAAA record type resources (all resource types I use). Exactly the same code ran perfectly fine a little while ago. It errors already on plan time. I've verified the API key and such basics - and was unable to find any issues there. Njalla also has not publicly noted that the API has changed. I have had authentication/authorization issues in the past, and am sure that's not at play here.

This is not an issue where I expect a fix, rather I want to verify if anyone else is having the same issue - as this still very well might be a /me issue.

**Comment by cozybear-dev** [comment]
Using the -refresh=false parameter, it works fine - so it's definitely something in the response it's receiving that contains a < which is whining about.

**Comment by Sighery** [comment]
Hey, sadly I've been unable to reproduce. I'm using provider version `0.10.0` and latest Terraform version. I just ran a plan without changes and also with changes and runs through just fine.

I took another look at the API keys and seems now Njalla offers more restrictions for domains, servers, API methods, etc. Perhaps you are using one of those and the API denied some requests? Although I would expect the response of the unauthorized API calls to also be a JSON. Error messages like `invalid character '<'` usually indicate you're not getting JSON back on an API call.

I'll try to take a look to see if I can improve trace logging somehow. For now, you should be able to manually run the edit/add API calls through Postman or similar with the API key that you use. [Here are Python and curl examples](https://njal.la/api/) (requires being logged in).

You'll need to set a header `Authorization: Njalla token-here`. All requests are `POST` against `https://njal.la/api/1/`. The body is always a JSON like this:

```
{
  "method": "method-name",
  "params": {
    "will": "depend",
    "on": "each",
    "method": "",
  },
}
```

In the previous link you can also find the relevant method name and parameters for  that method call. I suggest you try to add a new TXT to see what the response is. For that, you'll want the method `add-record`, which has the following signature for `params` and return type:

```
params: {
    domain: string
    name: string
    content: string
    ttl: int
    type: string
    ...
}
returns: {
    id: string
    content: string
    domain: string
    name: string
    ttl: int
    type: string
}
```

Try to run that with the same API key you use for that project, and see what the response it. That might tell you what's going on.

**Comment by cozybear-dev** [comment]
Thank you for your response!

I've done some more testing, and using postman on the same machine I run my Terraform from - I'm not having any issues. I also tried running Terraform with a brand new API token with no restrictions whatsoever, and had the same issue. Given that you are unable to reproduce the error I'm having, it must be something on my system somehow. I'll do some more digging.

**Comment by Sighery** [comment]
I'm thinking perhaps there's some kind of rate limit? I see you're creating quite a few entries with each. When I was first writing the provider I didn't implement anything for `each` functionality, so perhaps there's some options Terraform will allow to space out requests or retry them.

Could you try, with the same API key that is failing, to setup a new Terraform project, against the same domain, that just creates one single TXT record? If that works, then I'd be fairly confident is some rate limit.

**Comment by cozybear-dev** [comment]
Great suggestion. That works fine indeed. My recent expansions of the map I iterate over must be going over the rate limit now - lol.

**Comment by cozybear-dev** [comment]
As my Terraform project scoped to Njalla anyway, I chose to simply reduce the paralism at runtime; https://github.com/cozybear-dev/njalla-management/commit/ada235872d1be6353aa040ce5976098743fda3bc

Note that this "fix" is not a root cause fix, and will hurt Terraform performance heavily for no reason if you also manage resources with better rate limits.

Funnily enough only 1 works (1 QPS limit?), everything more produces the same ratelimit error. I would not be surprised if Njalla simply introduced this rate limit without announcement. 

Thank you again for your time and suggestions.

**Comment by Sighery** [comment]
Nice find. Completely forgot about Terraform's parallelism option.

I was looking and the [Terraform SDK has helpers for retries and timeouts](https://developer.hashicorp.com/terraform/plugin/sdkv2/resources/retries-and-customizable-timeouts). So that would be the proper solution, for this provider to implement some retry logic on the resources that can be rate limited.

That being said, I don't have much time to work on this project, so not quite sure when I'll get to implementing retries.
